// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EventDetectPlayerLocation","status":true,"description":"v1.5 Detects the player's location in parallel to the event's location,\r\nand checks the distance between the event and the player.","parameters":{}}
];
